src/Entity/Comments.php
<?php

namespace App\Entity;

use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Gedmo\Mapping\Annotation\Slug;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use App\Repository\VideosRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: VideosRepository::class)]
#[Vich\Uploadable]
class Comments
{
	use TimestampableEntity;
	
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;
	
    #[ORM\Column(length: 255)]
    private ?string $content = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Videos $video = null;
	
	public function __construct()
                      {
                          $this->createdAt = new \DateTimeImmutable();
                      }
	
    public function getIdComment(): ?int
    {
        return $this->id;
    }
	
    public function getContentComment(): ?string
    {
        return $this->content;
    }

    public function setContentComment(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getVideo(): ?Videos
    {
        return $this->video;
    }

    public function setVideo(?Videos $video): static
    {
        $this->video = $video;

        return $this;
    }
}

src/Entity/Videos.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Gedmo\Mapping\Annotation\Slug;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use App\Repository\VideosRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: VideosRepository::class)]
#[Vich\Uploadable]
class Videos
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $genre = null;

    #[ORM\Column(length: 255)]
    private ?string $thumbnail = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $duree = null;

    #[ORM\Column(length: 150, unique: true)]
    #[Slug(fields: ['title'])]
    private ?string $slug = null;

    #[Assert\File(
        maxSize: '1000m',
        extensions: [
            'mp4',
            'mp3',
            'mov',
            'webm'
        ],
        extensionsMessage: 'Please upload a valid video or mp3 file.',
    )]
    // NOTE: This is not a mapped field of entity metadata, just a simple property.
    #[Vich\UploadableField(mapping: 'videos', fileNameProperty: 'videoName', size: 'videoSize')]
    private ?File $videoFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $videoName = null;

    #[ORM\Column(nullable: true)]
    private ?int $videoSize = null;

    #[ORM\ManyToOne(inversedBy: 'videos')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'video', targetEntity: Comments::class)]
    private Collection $comments;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): static
    {
        $this->genre = $genre;

        return $this;
    }

    public function getThumbnail(): ?string
    {
        return $this->thumbnail;
    }

    public function setThumbnail(string $thumbnail): static
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }

    public function getDuree(): ?\DateTimeInterface
    {
        return $this->duree;
    }

    public function setDuree(?\DateTimeInterface $duree): static
    {
        $this->duree = $duree;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $videoFile
     */
    public function setVideoFile(?File $videoFile = null): void
    {
        $this->videoFile = $videoFile;

        if (null !== $videoFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getVideoFile(): ?File
    {
        return $this->videoFile;
    }

    public function setVideoName(?string $videoName): void
    {
        $this->videoName = $videoName;
    }

    public function getVideoName(): ?string
    {
        return $this->videoName;
    }

    public function setVideoSize(?int $videoSize): void
    {
        $this->videoSize = $videoSize;
    }

    public function getVideoSize(): ?int
    {
        return $this->videoSize;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setVideo($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getVideo() === $this) {
                $comment->setVideo(null);
            }
        }

        return $this;
    }
}

src/Form/VideoType.php
<?php

namespace App\Form;

use App\Entity\Videos;
use Vich\UploaderBundle\Form\Type\VichFileType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;

class VideoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
			->add('nom', TextType::class)
            ->add('title', TextType::class)
			->add('description', TextType::class)
			->add('genre', ChoiceType::class, [
				'choices' => [
					'Meme' => 'meme',
					'Music' => 'music'
				]
			])
			->add('videoFile', VichFileType::class, [
				'required' => false,
				'allow_delete' => true,
            ])
            ->add('save', SubmitType::class)
        ;
    }
	
	public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Videos::class,
        ]);
    }
}

src/Controller/VideoController.php
<?php

namespace App\Controller;

use App\Form\SearchType;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use App\Repository\UserRepository;
use App\Repository\CommentsRepository;

use App\Entity\User;
use App\Entity\Comments;
use App\Entity\Videos;
use App\Form\VideoType;
use App\Form\CommentType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Acme\AccountBundle\Form\Type\RegistrationType;
use Acme\AccountBundle\Form\Model\Registration;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Component\HttpFoundation\Request;
use function Symfony\Component\String\u;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\VideosRepository;

use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class VideoController extends AbstractController
{
	public function __construct(
        private bool $isDebug
    )
    {}
	
	#[Route('/browse/{genre?}', name: 'app_browse')]
	public function browse(SessionInterface $session, VideosRepository $videoRepository, Request $request, User $username = null, string $genre = null, AuthenticationUtils $authenticationUtils): Response
    {
		$this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        //$genre = $slug ? u(str_replace('-', ' ', $slug))->title(true) : null;
        $queryBuilder = $videoRepository->createOrderedByQueryBuilder($genre, $username);
        $adapter = new QueryAdapter($queryBuilder);
        $pagerfanta = Pagerfanta::createForCurrentPageWithMaxPerPage(
            $adapter,
            $request->query->get('page', 1),
            9
        );

        $formSearch = $this->createForm(SearchType::class);

        $formSearch->handleRequest($request);

        if ($formSearch->isSubmitted() && $formSearch->isValid()) {
            // data is an array with "name", "email", and "message" keys
            $data = $formSearch->getData();
			return $this->redirectToRoute('app_search', [
				'dataSearch' => $data,
				'formSearch' => $formSearch,
			]);
        }

		
        return $this->render('vinyl/browse.html.twig', [
            'formSearch' => $formSearch,
			'genre' => $genre,
            'pager' => $pagerfanta,
        ]);
    }

    #[Route('/myvideos/{genre?}', name: 'app_browse_myvideos')]
    public function myVideos(Request $request, VideosRepository $videoRepository, string $genre = null): Response
    {
        $formSearch = $this->createForm(SearchType::class);

        $formSearch->handleRequest($request);

        if ($formSearch->isSubmitted() && $formSearch->isValid()) {
            // data is an array with "name", "email", and "message" keys
            $data = $formSearch->getData();
            return $this->redirectToRoute('app_search', [
                'dataSearch' => $data,
                'formSearch' => $formSearch,
            ]);
        }

        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $username = $this->getUser();

        $queryBuilder = $videoRepository->createOrderedByQueryBuilder($genre, $username);
        $adapter = new QueryAdapter($queryBuilder);
        $pagerfanta = Pagerfanta::createForCurrentPageWithMaxPerPage(
            $adapter,
            $request->query->get('page', 1),
            9
        );

        return $this->render('vinyl/browsemyvideos.html.twig', [
            'genre' => $genre,
            'pager' => $pagerfanta,
            'formSearch' => $formSearch,
        ]);
    }
	
	#[Route('/video/newform', name: 'app_video_new_form')]
	public function new(Request $request, EntityManagerInterface $entityManager, SessionInterface $session, UserRepository $repository, AuthenticationUtils $authenticationUtils): Response
	{
		$this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
		
		$username = $this->getUser();

        if($username->isIsVerified() == false){
            $this->addFlash('danger', 'Please verify your account via the link sent to your email.');
            return $this->redirectToRoute('app_prof_show');
        }

        $formSearch = $this->createForm(SearchType::class);

        $formSearch->handleRequest($request);

        if ($formSearch->isSubmitted() && $formSearch->isValid()) {
            // data is an array with "name", "email", and "message" keys
            $data = $formSearch->getData();
			return $this->redirectToRoute('app_search', [
				'dataSearch' => $data,
				'formSearch' => $formSearch,
			]);
        }
		
		$video = new Videos();
        $video->setUser($username);

        $form = $this->createForm(VideoType::class, $video);
		
		$form->handleRequest($request);
		if ($form->isSubmitted() && $form->isValid()) {
			$listeExt = array('.mp4','.mov','.webm');
			$lien = str_replace($listeExt, ".png", $video->getTitle());
			$video->setThumbnail($lien);
            
			// $form->getData() holds the submitted values
            // but, the original `$user` variable has also been updated
            $video = $form->getData();
			
			$entityManager->persist($video);
			$entityManager->flush();
			
			
			
			return $this->redirectToRoute('app_video_new', [
				'video' => $video,
				'slug' => $video->getSlug(),
			]);
		}
		
		return $this->render('video/videoaddForm.html.twig', [
			'formSearch' => $formSearch,
			'form2' => $form,
		]);
	}
	
    #[Route('/video/new/{slug}', name: 'app_video_new')]
    public function newshow(Request $request, SessionInterface $session, Videos $video, AuthenticationUtils $authenticationUtils): Response
    {
		$this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
		
		$username = $this->getUser();

        $formSearch = $this->createForm(SearchType::class);

        $formSearch->handleRequest($request);

        if ($formSearch->isSubmitted() && $formSearch->isValid()) {
            // data is an array with "name", "email", and "message" keys
            $data = $formSearch->getData();
			return $this->redirectToRoute('app_search', [
				'dataSearch' => $data,
				'formSearch' => $formSearch,
			]);
        }
		
		return $this->render('video/videoadd.html.twig', [
			'formSearch' => $formSearch,
			'video' => $video,
		]);
    }
	
	#[Route('/video/{slug}', name: 'app_video_show')]
    public function show(SessionInterface $session, Videos $video, Security $security, CommentsRepository $commentRepository, Request $request, EntityManagerInterface $entityManager, UserRepository $repository, AuthenticationUtils $authenticationUtils): Response
	{
		$this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
		
		$username = $this->getUser();

        $formSearch = $this->createForm(SearchType::class);

        $formSearch->handleRequest($request);

        if ($formSearch->isSubmitted() && $formSearch->isValid()) {
            // data is an array with "name", "email", and "message" keys
            $data = $formSearch->getData();
			return $this->redirectToRoute('app_search', [
				'dataSearch' => $data,
				'formSearch' => $formSearch,
			]);
        }
		
		$comment = new Comments();
        $comment->setUser($username);
        $comment->setVideo($video);
		
		$formcom = $this->createForm(CommentType::class, $comment);
		
		$formcom->handleRequest($request);
		if ($formcom->isSubmitted() && $formcom->isValid()) {
			// $formcom->getData() holds the submitted values
            // but, the original `$comment` variable has also been updated
            $comment = $formcom->getData();

            // ... performcom some action, such as saving the comment to the database
			$entityManager->persist($comment);
			$entityManager->flush();
			
			unset($comment);
			unset($formcom);
			$comment = new Comments();
			$formcom = $this->createForm(CommentType::class, $comment);
			
			
			
			return $this->redirectToRoute('app_video_show', [
				'slug' => $video->getSlug(),
				'formcom' => $formcom,
				'video' => $video,
			]);
		}
		
        $queryBuilder = $commentRepository->commentTaker($video->getId());
        $adapter = new QueryAdapter($queryBuilder);
        $pagerfanta = Pagerfanta::createForCurrentPageWithMaxPerPage(
            $adapter,
            $request->query->get('page', 1),
            10
        );

        return $this->render('video/show.html.twig', [
			'formSearch' => $formSearch,
			'formcom' => $formcom,
			'video' => $video,
			'pager' => $pagerfanta,
        ]);
    }
}

templates/video/_recordSvg.html.twig
<svg width="100%" height="100%" viewBox="0 0 496 496" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <linearGradient x1="50%" y1="0%" x2="50%" y2="100%" id="linearGradient-1">
            <stop stop-color="#C380F3" offset="0%"></stop>
            <stop stop-color="#4A90E2" offset="100%"></stop>
        </linearGradient>
    </defs>
    <g id="Mixed-Vinyl" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Group">
            <g id="record-vinyl" fill="#000000" fill-rule="nonzero">
                <path d="M248,144 C190.562386,144 144,190.562386 144,248 C144,305.437614 190.562386,352 248,352 C305.437614,352 352,305.437614 352,248 C352,190.562386 305.437614,144 248,144 L248,144 Z M248,272 C234.745166,272 224,261.254834 224,248 C224,234.745166 234.745166,224 248,224 C261.254834,224 272,234.745166 272,248 C272,261.254834 261.254834,272 248,272 Z M248,0 C111,0 0,111 0,248 C0,385 111,496 248,496 C385,496 496,385 496,248 C496,111 385,0 248,0 Z M248,376 C177.307552,376 120,318.692448 120,248 C120,177.307552 177.307552,120 248,120 C318.692448,120 376,177.307552 376,248 C376,281.947711 362.514324,314.505012 338.509668,338.509668 C314.505012,362.514324 281.947711,376 248,376 Z" id="Shape"></path>
            </g>
            <g id="record-vinyl" transform="translate(144.000000, 144.000000)" fill="url(#linearGradient-1)" fill-rule="nonzero">
                <path d="M104,0 C46.562386,0 0,46.562386 0,104 C0,161.437614 46.562386,208 104,208 C161.437614,208 208,161.437614 208,104 C208,46.562386 161.437614,0 104,0 L104,0 Z M104,128 C90.745166,128 80,117.254834 80,104 C80,90.745166 90.745166,80 104,80 C117.254834,80 128,90.745166 128,104 C128,117.254834 117.254834,128 104,128 Z" id="Shape"></path>
            </g>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="235"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="215"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="195"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="175"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="155"></circle>
        </g>
    </g>
</svg>

templates/video/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ video.nom }} | VideoTube{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="d-inline me-3">{{ video.nom }}</h1>
        <div class="row mt-5">
			<div class="col-12 col-md-12" style="margin-bottom:30px;">
				<link rel="stylesheet" href="/assets/styles/videoplayer.css" />
				<figure id="videoContainer" data-fullscreen="false">
					<video id="video" class="video-js vjs-theme-city" width="800" height="500" controls preload="metadata">
						<source src="/vid/{{ video.videoName }}" type="video/mp4">
						<source src="/vid/{{ video.videoName }}" type="video/webm">
						<source src="/vid/{{ video.videoName }}" type="video/ogg">
						Problème vidéo.
						<object type="application/x-shockwave-flash" data="flash-player.swf?videoUrl=/vid/{{ video.videoName }}" width="1024" height="576">
							<param name="movie" value="flash-player.swf?videoUrl=/vid/{{ video.videoName }}" />
							<param name="allowfullscreen" value="true" />
							<param name="wmode" value="transparent" />
							<param name="flashvars" value="controlbar=over&amp;image=/vid/thumbnail/{{ video.getThumbnail() }}&amp;file=flash-player.swf?/vid/{{ video.videoName }}" />
							<img alt="Tears of Steel poster image" src="/vid/thumbnail/{{ video.getThumbnail() }}" width="1024" height="428" title="No video playback possible, please download the video from the link below" />
						</object>
					</video>
					<div id="video-controls" class="controls" data-state="hidden">
						<button id="playpause" type="button" data-state="play"></button>
						<button id="stop" type="button" data-state="stop"></button>
						<div class="progress">
						<progress id="progress" value="0" min="0">
							<span id="progress-bar"></span>
						</progress>
						</div>
						<button id="mute" type="button" data-state="mute"></button>
						<button id="volinc" type="button" data-state="volup"></button>
						<button id="voldec" type="button" data-state="voldown"></button>
						<button id="fs" type="button" data-state="go-fullscreen"></button>
					</div>
				</figure>
				<script src="/assets/videoplayer.js"></script>
            </div>
            <div class="col-md-12" style="margin-top:10px;">
				<a href="{{ path('app_prof_show_other', { 'id': video.user.id }) }}">
					{% if video.user.pfpName == '' %}
						<i class="fas fa-user-astronaut p-2" style="color:grey;border: solid 2px grey; border-radius: 50px; font-size: 50px;"></i>
					{% else %}
						<img src="{{ asset('pfp/'~video.user.pfpName) }}" style="width:100px;height:100px;border-radius:50%;object-fit:cover;">
					{% endif %}
					<strong>{{ video.user.username }}</strong>
				</a>
                <div>
					<p>{{ video.description }}</p>
				</div>
			</div>
			<div class="col-md-12" style="margin-top:20px;">
				{% if formcom != 'undefined' %}
					{{ form(formcom) }}
				{% endif %}
				{% for comment in pager %}
					<div class="row" style="margin-bottom:25px;background-color:#222f36;border-radius:25px;">
						<div class="col col-md-1" style="text-align:center;margin-top:10px;">
							<a href="/profile/{{ comment.user.id }}">
								{% if comment.user.pfpName == '' %}
									<i class="fas fa-user-astronaut p-2" style="color:grey;border: solid 2px grey; border-radius: 50px; font-size: 50px;"></i>
								{% else %}
									<img src="/pfp/{{ comment.user.pfpName }}" style="width:70px;height:70px;border-radius:50%;object-fit:cover;">
								{% endif %}
							</a>
						</div>
						<div class="col col-md-11">
							<div>
								<a href="/profile/{{ comment.user.id }}"><strong>{{ comment.user.username }}</strong></a>
								<p class="mt-2"><strong>{{ comment.contentComment }}</strong><br><span>{{ comment.createdAt|ago }}</span></p>
							</div>
						</div>
					</div>
				{% endfor %}
				
				{#{% if pager.hasNextPage %}
                    <turbo-frame id="video-browse-list-{{ pager.nextPage }}" src="{{ pagerfanta_page_url(pager, pager.nextPage) }}" loading="lazy"></turbo-frame>
                {% endif %}#}
			</div>
        </div>
    </div>
{% endblock %}

templates/video/videoadd.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ video.nom }} | VideoTube{% endblock %}

{% block body %}
<script>
var videoId = 'video';
var scaleFactor = null;
var snapshots = [];

/**
 * Captures a image frame from the provided video element.
 *
 * @param {Video} video HTML5 video element from where the image frame will be captured.
 * @param {Number} scaleFactor Factor to scale the canvas element that will be return. This is an optional parameter.
 *
 * @return {Canvas}
 */
function capture(video, scaleFactor) {
	if(scaleFactor == null){
		scaleFactor = 1.5;
	}
	var w = video.videoWidth * scaleFactor;
	var h = video.videoHeight * scaleFactor;
	var canvas = document.createElement('canvas');
		canvas.width  = w;
	    canvas.height = h;
		canvas.id = "adown";
	var ctx = canvas.getContext('2d');
		ctx.drawImage(video, 0, 0, w, h);
    return canvas;
} 

/**
 * Invokes the <code>capture</code> function and attaches the canvas element to the DOM.
 */
function shoot(){
	var video  = document.getElementById(videoId);
	var output = document.getElementById('output');
	var canvas = capture(video, scaleFactor);
		canvas.onclick = function(){
			window.open(this.toDataURL());
		};
	snapshots.unshift(canvas);
	output.innerHTML = '';
	for(var i=0; i<1; i++){
		output.appendChild(snapshots[i]);
	}
	
	var videoRating = document.querySelector('.js-video-rating');
    var videoNom = JSON.parse(videoRating.dataset.video);
	
	/*var videoRating = document.querySelector('.js-video-rating');
    var videoNom = JSON.parse(videoRating.dataset.video);
	
	var download = document.createElement("a");
		download.id = "";
		download.style = "width:150px;height:50px;";
		download.href = "http://127.0.0.1:8000/video/new";
		download.download = `${videoNom}.png`;
		download.textContent = "Prendre cette miniature.";
	var saut = document.createElement("br");
	output.appendChild(saut);
	output.appendChild(download);*/
}
</script>
    <div class="container">
        <h1 class="d-inline me-3" id="videoNom">{{ video.nom }}</h1>
        <div class="row mt-5">
            <div class="col-12 col-md-12">
                <video id="video" class="video-js vjs-theme-city" width="800" height="500" autoplay controls>
					<source src="/vid/{{ video.videoName }}" type="video/mp4">
					<source src="/vid/{{ video.videoName }}" type="video/webm">
					<source src="/vid/{{ video.videoName }}" type="video/ogg">
					Problème vidéo.
				</video>
            </div>
			
			<div class="js-video-rating"
				data-video="{{ video.nom|serialize(format = 'json') }}"
			>
			
			<h1>For the thumbnail, you can : </h1>
            <div class="col-md-6" style="margin-top:10px;">
				<h3>Upload a file...</h3>
				
            </div>
			<div class="col-md-6" style="margin-top:10px;">
				<h3>or click the capture button to have an image of the time of the video.</h3>
				<button id="btnDirect" onclick="shoot()" class="btn btn-primary" style="width:100px;height:50px;margin-bottom:20px;">Capture</button>
            </div>
			<div id="output"></div>
        	</div>
    	</div>
	</div>
{% endblock %}

templates/video/videoaddForm.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add a new video | VideoTube{% endblock %}

{% block body %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div>
				{{ form(form2) }}
			</div>
		</div>
	</div>
</div>
{% endblock %}